name: build resources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zerocluster/core
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          npm explore @softvisio/core -- npm run build
        shell: bash
        working-directory: /var/local/package
